baseURL: https://cnily.me/
defaultContentLanguage: zh-cn
languageCode: zh-CN
# æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
hasCJKLanguage: true
# æ›´æ”¹ä½¿ç”¨ Hugo æ„å»ºç½‘ç«™æ—¶ä½¿ç”¨çš„é»˜è®¤ä¸»é¢˜
theme: DoIt
# ç½‘ç«™æ ‡é¢˜ï¼ˆå¯¼èˆªæ ï¼‰ - å·²åœ¨è¯­è¨€å¤„è®¾ç½®
# title: Cnily03's Blog

#ä½œè€…
author:
  name: 'Cnily03'
  link: 'https://github.com/Cnily03'
# ç½‘ç«™å…³é”®è¯
keywords:
  - Blog
  - Cnily03
# å¼€å¯ PWA æ”¯æŒ
enablePWA: false
# ç‰ˆæƒä¿¡æ¯
license: <a data-tooltip="License might be changed if particularly declared" class="tooltip tooltip-bottom" rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>

# æ˜¯å¦ä½¿ç”¨ robots.txt
enableRobotsTXT: true
# æ˜¯å¦ä½¿ç”¨ git ä¿¡æ¯
enableGitInfo: true
# æ˜¯å¦ä½¿ç”¨ emoji ä»£ç 
enableEmoji: true
# æœ€åæ›´æ–°æ—¥æœŸ
frontmatter:
  lastmod: ['lastmod', ':fileModTime']

params:
  # ç½‘ç«™åç§°
  title: Blog | Cnily03
  # ç½‘ç«™æè¿°
  description: Cnily03 çš„ä¸ªäººåšå®¢
  # DoIt ä¸»é¢˜ç‰ˆæœ¬
  version: 0.2.X
  # ç½‘ç«™é»˜è®¤ä¸»é¢˜æ ·å¼ ("light", "dark", "black", "auto")
  defaultTheme: auto
  # æ—¥æœŸæ ¼å¼
  dateFormat: 2006-01-02

  # é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
  header:
    # æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ("fixed", "normal", "auto")
    desktopMode: fixed
    # ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ("fixed", "normal", "auto")
    mobileMode: auto
    # ä¸»é¢˜åˆ‡æ¢æ¨¡å¼ ("switch", "select")
    themeChangeMode: switch
    # é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
    title:
      # LOGO çš„ URL
      logo: ''
      # æ ‡é¢˜åç§°
      name: Cnily03 Home
      # åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      pre: "<i class='cc cc-jw-bold' style='margin-right: .5rem'></i>"
      # åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
      post: ''
      # æ˜¯å¦ä¸ºæ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit: true

  # é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
  footer:
    enable: true
    # è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
    custom: ''
    # æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
    hugo: true
    # æ‰˜ç®¡æœåŠ¡ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
    # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
    hostedOn: ''
    # æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
    copyright: true
    # æ˜¯å¦æ˜¾ç¤ºä½œè€…
    author: true
    # ç½‘ç«™åˆ›ç«‹å¹´ä»½
    since: 2022
    # ICP å¤‡æ¡ˆä¿¡æ¯, ä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
    icp: ''
    # å…¬å®‰å¤‡æ¡ˆä¿¡æ¯, ä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
    gongan:
    # è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
    license: <a data-tooltip="License might be changed if particularly declared" class="tooltip" rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>

  # ä¸»é¡µé…ç½®
  home:
    # RSS æ–‡ç« æ•°ç›®
    rss: 10

    # ä¸»é¡µä¸ªäººä¿¡æ¯
    profile:
      enable: true
      # Gravatar é‚®ç®±, ç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
      gravatarEmail: ''
      # ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
      # å°†ä½ çš„å¤´åƒæ–‡ä»¶æ”¾ç½®äº static æˆ–è€… assets ç›®å½•ä¸‹
      # æ–‡ä»¶è·¯å¾„æ˜¯ç›¸å¯¹äº static æˆ–è€… assets ç›®å½•çš„
      # avatarURL: /images/avatar.webp
      avatarURL: https://img.cnily.top/avatar.png@webp
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ (æ”¯æŒ HTML æ ¼å¼)
      title: Cnily03
      # ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜
      subtitle: It's ãµã‚ãµã‚æ™‚é–“ ~
      # æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
      typeit: true
      # æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
      social: true
      # å…è´£å£°æ˜ (æ”¯æŒ HTML æ ¼å¼)
      disclaimer: ''

    # ä¸»é¡µæ–‡ç« åˆ—è¡¨
    posts:
      enable: true
      # ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
      paginate: 6

  # ç¤¾äº¤ä¿¡æ¯è®¾ç½®
  social:
    GitHub: Cnily03
    Zhihu: 'cnily03'
    Telegram: Cnily03
    Bilibili: '314148718'
    Email: contact@cnily.me
    RSS: true

  # æ–‡ç« é¡µé¢é…ç½®
  page:
    # æ˜¯å¦åœ¨ä¸»é¡µéšè—ä¸€ç¯‡æ–‡ç« 
    hiddenFromHomePage: false
    # æ˜¯å¦åœ¨æœç´¢ç»“æœä¸­éšè—ä¸€ç¯‡æ–‡ç« 
    hiddenFromSearch: false
    # æ˜¯å¦ä½¿ç”¨ twemoji
    twemoji: false
    # æ˜¯å¦ä½¿ç”¨ lightgallery
    lightgallery: true
    # æ˜¯å¦ä½¿ç”¨ ruby æ‰©å±•è¯­æ³•
    ruby: true
    # æ˜¯å¦ä½¿ç”¨ fraction æ‰©å±•è¯­æ³•
    fraction: true
    # æ˜¯å¦ä½¿ç”¨ fontawesome æ‰©å±•è¯­æ³•
    fontawesome: true
    # æ˜¯å¦åœ¨æ–‡ç« é¡µé¢æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£é“¾æ¥
    linkToMarkdown: true
    # é…ç½®æ–‡ç« åŸå§‹æ–‡ä»¶çš„é“¾æ¥
    # "https://github.com/user/repo/blob/main/{path}"
    linkToSource: https://github.com/Cnily03/cnily.me/blob/master/content/{path}?plain=1
    # é…ç½®ç¼–è¾‘æ–‡ç« çš„é“¾æ¥
    # "https://github.com/user/repo/edit/main/{path}"
    # "https://gitlab.com/user/repo/-/edit/main/{path}"
    # "https://bitbucket.org/user/repo/src/main/{ path}?mode=edit"
    linkToEdit: false
    # é…ç½®æäº¤é”™è¯¯çš„é“¾æ¥
    # "https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
    linkToReport: https://github.com/Cnily03/cnily.me/issues/new?labels=website,posts,bug&body=|Origin|File|%0A|-|-|%0A|[{title}]({url})|[ğŸ”—Github](https://github.com/Cnily03/cnily.me/blob/master/content/{path}?plain=1)|%0A---
    # æ˜¯å¦åœ¨ RSS ä¸­æ˜¾ç¤ºå…¨æ–‡å†…å®¹
    rssFullText: false
    # é¡µé¢æ ·å¼ ("normal", "wide")
    pageStyle: normal
    # æ˜¯å¦åœ¨æ–‡ç« å¼€å¤´æ˜¾ç¤ºç³»åˆ—å¯¼èˆª
    seriesNavigation: true

    # è¿‡æ—¶æ–‡ç« æç¤º
    outdatedArticleReminder:
      enable: false
      # å¦‚æœæ–‡ç« æœ€åæ›´æ–°äº x å¤©ä¹‹å‰ï¼Œæ˜¾ç¤ºæé†’
      reminder: 90
      # å¦‚æœæ–‡ç« æœ€åæ›´æ–°äº x å¤©ä¹‹å‰ï¼Œæ˜¾ç¤ºè­¦å‘Š
      warning: 180

    # ç›®å½•é…ç½®
    toc:
      enable: true
      # æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
      keepStatic: false
      # æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
      auto: false

    # ä»£ç é…ç½®
    code:
      # æ˜¯å¦æ˜¾ç¤ºä»£ç å—çš„å¤åˆ¶æŒ‰é’®
      copy: true
      # é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
      maxShownLines: 20

    # è¡¨æ ¼é…ç½®
    table:
      # æ˜¯å¦å¼€å¯è¡¨æ ¼æ’åº
      sort: true

    # KaTeX æ•°å­¦å…¬å¼
    math:
      enable: true
      # é»˜è®¤å—å®šç•Œç¬¦æ˜¯ $$ ... $$ å’Œ \\[ ... \\]
      blockLeftDelimiter: ''
      blockRightDelimiter: ''
      # é»˜è®¤è¡Œå†…å®šç•Œç¬¦æ˜¯ $ ... $ å’Œ \\( ... \\)
      inlineLeftDelimiter: ''
      inlineRightDelimiter: ''
      # KaTeX æ’ä»¶ copy_tex
      copyTex: true
      # KaTeX æ’ä»¶ mhchem
      mhchem: true

    # Mapbox GL JS é…ç½®
    mapbox:
      # Mapbox GL JS çš„ access token
      accessToken: ''
      # æµ…è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
      lightStyle: mapbox://styles/mapbox/light-v9
      # æ·±è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
      darkStyle: mapbox://styles/mapbox/dark-v9
      # æ˜¯å¦æ·»åŠ  NavigationControl
      navigation: true
      # æ˜¯å¦æ·»åŠ  GeolocateControl
      geolocate:
        true
        # æ˜¯å¦æ·»åŠ  ScaleControl
      scale: true
      # æ˜¯å¦æ·»åŠ  FullscreenControl
      fullscreen: true

    # æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
    share:
      enable: true
      Twitter: true
      Facebook: true
      Weibo: true

    # è¯„è®ºç³»ç»Ÿè®¾ç½®
    comment:
      enable: false

    # é¡µé¢ SEO é…ç½®
    seo:
      # å›¾ç‰‡ URL
      images: []
      # å‡ºç‰ˆè€…ä¿¡æ¯
      publisher:
        name: ''
        logoUrl: ''

    # ç›¸å…³æ–‡ç« æ¨èé…ç½®
    related:
      enable: false
      count: 5

    # ç¬¬ä¸‰æ–¹åº“é…ç½®
    library:
      css:
        # someCSS:
        # # æ›´å¤šç¬¬ä¸‰æ–¹åº“é…ç½®
        # someOtherCSS:
        # src: someOther.css
        # defer: true
        # attr: customAttribute
        # # ä½äº "assets/"
        # # æˆ–è€…
        # someCSS: 'https://cdn.example.com/some.css'
      js:
        # someJavaScript:
        # # æ›´å¤šç¬¬ä¸‰æ–¹åº“é…ç½®
        # someOtherJavaScript:
        #   src: someOther.js
        #   defer: true
        #   async: false
        #   attr: customAttribute
        # # ä½äº "assets/"
        # # æˆ–è€…
        # someJavaScript: 'https://cdn.example.com/some.js'

  # è‡ªå®šä¹‰è®¾ç½®
  custom:
    libraries:
      head:
        js:
          - src: /v/js/title2tooltip.js
            defer: true
          - src: /v/js/redirect.js
            defer: false
        css: /v/css/common.css
        raw:
      page-start:
        js: /third-parties/js/svg-inject.min.js
      page-end:
        js:
          - /v/js/auto-indent.js
          - /v/js/sponsor.js
        css: /v/css/sponsor.css
      footer-end:
        js: /v/js/naughty-footer.js

  # æœç´¢é…ç½®
  search:
    enable: true
    # æœç´¢å¼•æ“çš„ç±»å‹ ("lunr", "algolia", "fuse")
    type: fuse
    # æ–‡ç« å†…å®¹æœ€é•¿ç´¢å¼•é•¿åº¦
    contentLength: 4000
    # æœç´¢æ¡†çš„å ä½æç¤ºè¯­
    placeholder: ''
    # æœ€å¤§ç»“æœæ•°ç›®
    maxResultLength: 10
    # ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
    snippetLength: 50
    # æœç´¢ç»“æœä¸­é«˜äº®éƒ¨åˆ†çš„ HTML æ ‡ç­¾
    highlightTag: em
    # æ˜¯å¦åœ¨æœç´¢ç´¢å¼•ä¸­ä½¿ç”¨åŸºäº baseURL çš„ç»å¯¹è·¯å¾„
    absoluteURL: false

    algolia:
      index: ''
      appID: ''
      searchKey: ''

    fuse:
      # https://fusejs.io/api/options.html
      isCaseSensitive: false
      minMatchCharLength: 2
      findAllMatches: false
      location: 0
      threshold: 0.3
      distance: 100
      ignoreLocation: false
      useExtendedSearch: false
      ignoreFieldNorm: false

  # èµèµé…ç½®
  sponsor:
    enable: true
    bio: å¦‚æœä½ è§‰å¾—è¿™ç¯‡æ–‡ç« å¯¹ä½ æœ‰æ‰€å¸®åŠ©ï¼Œæ¬¢è¿èµèµ~
    # ä½ çš„èµèµé¡µé¢çš„åœ°å€
    link: https://space.bilibili.com/314148718
    # è‡ªå®šä¹‰ HTML
    custom: ''

  # TypeIt é…ç½®
  typeit:
    # æ¯ä¸€æ­¥çš„æ‰“å­—é€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
    speed: 100
    # å…‰æ ‡çš„é—ªçƒé€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
    cursorSpeed: 1000
    # å…‰æ ‡çš„å­—ç¬¦ (æ”¯æŒ HTML æ ¼å¼)
    cursorChar: '|'
    # æ‰“å­—ç»“æŸä¹‹åå…‰æ ‡çš„æŒç»­æ—¶é—´ (å•ä½æ˜¯æ¯«ç§’, "-1" ä»£è¡¨æ— é™å¤§)
    duration: 5000

  # Cookie è®¸å¯é…ç½®
  cookieconsent:
    enable: false
    # ç”¨äº Cookie è®¸å¯æ¨ªå¹…çš„æ–‡æœ¬å­—ç¬¦ä¸²
    content:
      message: ''
      dismiss: ''
      link: ''

# è¯­è¨€
languages:
  en:
    weight: 1
    title: Cnily03's Playground
    languageCode: en
    languageName: English
    # èœå•
    menu:
      main:
        - identifier: posts
          pre: ''
          post: ''
          name: Posts
          url: /posts/
          title: ''
          weight: 1
        - identifier: categories
          pre: ''
          post: ''
          name: Categories
          url: /categories/
          title: ''
          weight: 2
        - identifier: series
          pre: ''
          post: ''
          name: Series
          url: /series/
          title: ''
          weight: 3
        - identifier: tags
          pre: ''
          post: ''
          name: Tags
          url: /tags/
          title: ''
          weight: 4
        - identifier: window
          pre: ''
          post: ''
          name: Window
          url: /window/
          title: ''
          weight: 5
        - identifier: friends
          pre: ''
          post: ''
          name: Friends
          url: /friends/
          title: ''
          weight: 6
        - identifier: yuque
          pre: <span id="renew-redirect"></span><b>Yuque</b>
          post: ''
          name: ''
          url: https://b.cnily.me
          title: Yuque
          weight: 7
        - identifier: github
          pre: <i class='fab fa-github fa-fw'></i>
          post: ''
          name: ''
          url: https://github.com/Cnily03/cnily.me
          title: GitHub
          weight: 8
  zh-cn:
    weight: 2
    title: Cnily03 Home
    # ç½‘ç«™è¯­è¨€, ä»…åœ¨è¿™é‡Œ CN å¤§å†™
    languageCode: zh-CN
    languageName: ç®€ä½“ä¸­æ–‡
    # æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
    hasCJKLanguage: true
    menu:
      main:
        - identifier: posts
          pre: ''
          post: ''
          name: æ–‡ç« 
          url: /posts/
          title: ''
          weight: 1
        - identifier: categories
          pre: ''
          post: ''
          name: åˆ†ç±»
          url: /categories/
          title: ''
          weight: 2
        - identifier: series
          pre: ''
          post: ''
          name: ç³»åˆ—
          url: /series/
          title: ''
          weight: 3
        - identifier: tags
          pre: ''
          post: ''
          name: æ ‡ç­¾
          url: /tags/
          title: ''
          weight: 4
        - identifier: window
          pre: ''
          post: ''
          name: æ©±çª—
          url: /window/
          title: ''
          weight: 5
        - identifier: friends
          pre: ''
          post: ''
          name: å‹é“¾
          url: /friends/
          title: ''
          weight: 6
        - identifier: yuque
          pre: <span id="renew-redirect"></span><b>è¯­é›€</b>
          post: ''
          name: ''
          url: https://b.cnily.me
          title: è¯­é›€
          weight: 7
        - identifier: github
          pre: <i class='fab fa-github fa-fw'></i>
          post: ''
          name: ''
          url: https://github.com/Cnily03/cnily.me
          title: GitHub
          weight: 8

# Hugo è§£ææ–‡æ¡£çš„é…ç½®
markup:
  # è¯­æ³•é«˜äº®è®¾ç½®
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    # false æ˜¯å¿…è¦çš„è®¾ç½®
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses: false

  # Goldmark æ˜¯ Hugo 0.60 ä»¥æ¥çš„é»˜è®¤ Markdown è§£æåº“
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      # æ˜¯å¦åœ¨æ–‡æ¡£ä¸­ç›´æ¥ä½¿ç”¨ HTML æ ‡ç­¾
      unsafe: true

  # ç›®å½•è®¾ç½®
  tableOfContents:
    startLevel: 2
    endLevel: 6

# ä½œè€…é…ç½®
# author:

# ç½‘ç«™åœ°å›¾é…ç½®
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

# Permalinks é…ç½®
Permalinks:
  posts: posts/:slugorfilename

# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
mediaTypes:
  text/plain:
    suffixes:
      - md

# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false

# ç”¨äº Hugo è¾“å‡ºæ–‡æ¡£çš„è®¾ç½®
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML

# ç”¨äºåˆ†ç±»çš„è®¾ç½®
taxonomies:
  author: authors
  category: categories
  tag: tags
  series: series
